apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: song-service
  name: song-service
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8080
  selector:
    io.kompose.service: song-service
