apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: song-service
  name: song-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: song-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: song-service
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: POSTGRES_URL
              value: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
            - name: SERVICE_PORT
              value: "8080"
          image: song-service:latest
          name: song-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
