apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: streaming-service
  name: streaming-service
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8080
  selector:
    io.kompose.service: streaming-service
